.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject COMBAT
.in \w'AttackingXX\0\0\0\0'u
.s1
.L "Attacking ! "
Details for attack, assault, paradrop, board and lboard
.L "Damage   "
How much damage stuff does
.L "Fallout   "
The long lasting effects of nuclear war
.L "Flak * "
How flak works
.L "Hitchance   "
The chance of a projectile hitting its target
.s1
.L "assault * "
Attack coastal sector from ship
.L "attack * "
Sector vs. sector combat
.L "board * "
Board enemy ship
.L "bomb * "
Dispose of inconvenient enemy assets with air power.
.L "fire * "
Fire artillery from sector/ship/unit on sector/ship
.L "lboard * "
Board enemy land unit
.L "paradrop   "
Attack a sector from the air
.L "pboard * "
Board enemy plane
.L "spy * "
Snoop on adjacent enemy sectors
.L "strength   "
Report defensive strengths of sectors
.L "torpedo * "
Slip a torpedo to some poor sucker (from a sub or ship)
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
