.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject COMMERCE
.in \w'marketXX\0\0\0\0'u
.s1
.L "buy   "
Purchase commodities from the world market
.L "market   "
Report current selling prices in the world market
.L "reset   "
Reset the price of a product on the market
.L "sell   "
Sell commodities on the world market
.L "set   "
Establish price for a ship, plane, land unit or nuke
.L "trade   "
Buy ships, planes, land units or nukes
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
