.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject COMMODITIES
.in \w'sinfrastructureXX\0\0\0\0'u
.s1
.L "Item-types * "
Description of the different types of items
.s1
.L "census * "
Report contents of sectors
.L "commodity * "
Report commodities in sectors
.L "drop   "
Use planes to drop commodities in your own sectors
.L "grind   "
Grind bars back into dust
.L "improve * "
Improve the infrastructure of a sector
.L "move * "
Transport ore, civilians, guns, etc
.L "sinfrastructure * "
Report infrastructure of sectors
.L "test   "
Check the effect of a proposed move
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
