.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject DEITY
.in \w'setresourceXX\0\0\0\0'u
.s1
.L "add   "
Add/Remove a country in the game
.L "disable   "
Disable Updates
.L "edit   "
Edit sectors, ships, planes, land units, nukes or countries
.L "enable   "
Enable updates
.L "force   "
Force an update
.L "give   "
Give(take) Commodities
.L "newcap   "
Place a pair of sanctuaries
.L "peek   "
Display some deity-only statistics for sectors
.L "players   "
List players currently connected to the game
.L "reload   "
Reload server configuration and reopen log files
.L "setresource + "
Change resources of a sector
.L "setsector + "
Change stats of a sector
.L "shutdown   "
Shut down the server
.L "swapsector   "
Swap two sectors
.L "turn   "
Turn game on or off, or change the login message
.s1
.L "God   "
Tips on being God
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by + are obsolete.
