.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject DETECTION
.in \w'coastwatchXX\0\0\0\0'u
.s1
.L "coastwatch * "
Check from sectors for nearby ships
.L "llookout * "
Check from units for other units, planes and/or sector types
.L "lookout * "
Check from ships for other ships and/or sector types
.L "lradar   "
Use a radar unit's radar
.L "radar * "
Perform radar scan from ship or sector
.L "recon   "
Use planes to take a look around
.L "satellite   "
Download data from a reconnaissance satellite
.L "skywatch   "
Check from sectors for nearby satellites
.L "sonar * "
Use sonar to look for ships
.L "spy * "
Snoop on adjacent enemy sectors
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
