.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject INTRODUCTION
.in \w'SuggestionsXX\0\0\0\0'u
.s1
.L "Basics * "
The basic rules for playing Empire
.L "Expert   "
Advice to expert Empire players
.L "Guide *!"
User's Guide to Empire
.L "Hints   "
Hints to help you play Empire better
.L "Kill * "
How to kill your process on the server
.L "Novice *!"
Advice for Novices
.L "Overview * "
An Overview of the Game
.L "Suggestions   "
Suggestions for enhancements to the game
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
