.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject LANDUNITS
.in \w'MaintenanceXX\0\0\0\0'u
.s1
.L "Land-units *!"
How to use land units
.L "Maintenance   "
The cost to maintain ships, planes, and land units.
.L "Mobility   "
How much mobility stuff costs
.L "Railroad   "
How railroads work
.L "Spies   "
How spies work
.L "Unit-types * "
Description of the different types of land units
.s1
.L "army   "
Designate members of an \*Qarmy\*U
.L "assault * "
Attack coastal sector from ship
.L "attack * "
Sector vs. sector combat
.L "board * "
Board enemy ship
.L "build * "
Build ships, planes, land units, nuclear weapons or bridges
.L "fortify * "
Fortify a land unit
.L "land * "
Report status of land units
.L "lbmap * "
Big map of all your worldly knowledge around a land unit
.L "lboard * "
Board enemy land unit
.L "lcargo * "
List the commodities on board your units
.L "ldump   "
Dump raw land unit information
.L "lload * "
Load things onto land units
.L "llookout * "
Check from units for other units, planes and/or sector types
.L "lmap * "
Map around a land unit
.L "lmine   "
Mine a sector with an engineering unit
.L "lost * "
Report lost items
.L "lradar   "
Use a radar unit's radar
.L "lretreat   "
Set retreat conditions/paths for units or armies
.L "lstat * "
Report statistics of unit, army or units in a given area
.L "ltend   "
Transfer things between a unit and the ship carrying it
.L "lunload * "
Unload things from land units
.L "march * "
Move a land unit or units
.L "mission * "
Assign a mission to a ship/plane/unit
.L "morale   "
Change the retreat percentage of a unit
.L "sabotage * "
Damage enemy territory with spy unit
.L "scrap * "
Scrap a ship, plane, or land unit
.L "scuttle * "
Destroy a ship, plane, or unit
.L "show * "
Characteristics of sectors, units, updates and more
.L "start   "
Resume production and repairs
.L "stop   "
Stop production and repairs
.L "supply * "
Cause a unit to draw supplies
.L "upgrade   "
Update the tech of a ship/unit/plane to the current tech level
.L "work   "
Use engineers to raise sector efficiency
.L "xdump   "
Extended dump of everything under the sun
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
