.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject LOANS
.in \w'financialXX\0\0\0\0'u
.s1
.L "collect   "
Foreclose an overdue loan
.L "consider   "
Accept, decline or postpone consideration of a loan
.L "financial   "
Show all the outstanding loans in the world
.L "ledger   "
Report on outstanding loans
.L "offer   "
Offer a loan to another country
.L "repay   "
Repay a loan (all or part)
.L "shark   "
Purchase defaulted loan
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
