.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject MAPS
.in \w'sharebmapXX\0\0\0\0'u
.s1
.L "bdes   "
Manually change your bmap
.L "bestpath   "
Show the best path from one sector to another
.L "bmap * "
Big map of all your worldly knowledge
.L "lbmap * "
Big map of all your worldly knowledge around a land unit
.L "lmap * "
Map around a land unit
.L "map * "
Generate a map showing sector types, seas, etc
.L "nbmap * "
Big map of all your worldly knowledge around a nuke
.L "nmap * "
Generate a map showing new sector types or around a nuke
.L "origin   "
Change the origin of your country's coordinate system
.L "pbmap * "
Big map of all your worldly knowledge around a plane
.L "pmap * "
Get a map around a plane
.L "realm * "
Print out or modify one of your \*Qrealms\*U
.L "sbmap * "
Big map of all your worldly knowledge around a ship
.L "sect   "
Show only sectors owned by you in map form
.L "sharebmap   "
Share parts of your bmap with another country
.L "smap * "
Get a map around a ship
.L "survey   "
Show distributions in map form
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
