.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject NUKES
.in \w'NukeMtypesXX\0\0\0\0'u
.s1
.L "Fallout   "
The long lasting effects of nuclear war
.L "Mobility   "
How much mobility stuff costs
.L "Nuke-types   "
Description of different kinds of nuclear weapons
.s1
.L "arm   "
Load nuclear weapons onto planes or missiles
.L "build * "
Build ships, planes, land units, nuclear weapons or bridges
.L "harden   "
Place missiles into protective silos
.L "launch   "
Launch missiles or satellites
.L "lost * "
Report lost items
.L "nbmap * "
Big map of all your worldly knowledge around a nuke
.L "ndump   "
Dump raw nuke information
.L "nmap * "
Generate a map showing new sector types or around a nuke
.L "nuke   "
Report status of nukes
.L "show * "
Characteristics of sectors, units, updates and more
.L "start   "
Resume production and repairs
.L "stockpile   "
Designate members of a \*Qstockpile\*U
.L "stop   "
Stop production and repairs
.L "transport * "
Move planes or nuclear devices around
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
