.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject OCCUPATION
.in \w'SectorMownershipXX\0\0\0\0'u
.s1
.L "Citizens * "
Work, starvation, and general management of your citizens
.L "Guerrilla   "
Guerrilla warfare
.L "Sector-ownership * "
Sector ownership
.s1
.L "anti * "
anti-terrorist actions
.L "convert * "
Change conquered civilians into uncompensated workers
.L "shoot * "
Dispose of enemy civilians or uncompensated workers
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
