.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject PLANES
.in \w'InterceptionXX\0\0\0\0'u
.s1
.L "Flak * "
How flak works
.L "Interception   "
How plane interception works
.L "Maintenance   "
The cost to maintain ships, planes, and land units.
.L "Mobility   "
How much mobility stuff costs
.L "Nuke-types   "
Description of different kinds of nuclear weapons
.L "Plane-types *!"
Description of different kinds of planes
.s1
.L "arm   "
Load nuclear weapons onto planes or missiles
.L "bomb * "
Dispose of inconvenient enemy assets with air power.
.L "build * "
Build ships, planes, land units, nuclear weapons or bridges
.L "disarm   "
Remove a nuclear warhead from a plane or missile
.L "drop   "
Use planes to drop commodities in your own sectors
.L "fly * "
Fly planes from sector/ship to sector/ship and bomb or snoop
.L "harden   "
Place missiles into protective silos
.L "launch   "
Launch missiles or satellites
.L "lost * "
Report lost items
.L "mission * "
Assign a mission to a ship/plane/unit
.L "ndump   "
Dump raw nuke information
.L "nuke   "
Report status of nukes
.L "paradrop   "
Attack a sector from the air
.L "pbmap * "
Big map of all your worldly knowledge around a plane
.L "pboard * "
Board enemy plane
.L "pdump   "
Dump raw plane information
.L "plane * "
Report status of planes
.L "pmap * "
Get a map around a plane
.L "pstat * "
Report statistics of plane, wing or planes in a give area
.L "range   "
Edit the range of a plane
.L "recon   "
Use planes to take a look around
.L "satellite   "
Download data from a reconnaissance satellite
.L "scrap * "
Scrap a ship, plane, or land unit
.L "scuttle * "
Destroy a ship, plane, or unit
.L "show * "
Characteristics of sectors, units, updates and more
.L "start   "
Resume production and repairs
.L "stop   "
Stop production and repairs
.L "sweep   "
Use planes to remove mines from sea sectors
.L "transport * "
Move planes or nuclear devices around
.L "upgrade   "
Update the tech of a ship/unit/plane to the current tech level
.L "wingadd   "
Designate members of a \*Qwing\*U
.L "xdump   "
Extended dump of everything under the sun
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
