.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject PLAYING
.in \w'SelectorXX\0\0\0\0'u
.s1
.L "BTU   "
How BTUs are generated
.L "Selector * "
Selectors you can use in Empire conditionals
.L "Sheep   "
Ovis aries
.L "Syntax * "
The Empire command syntax
.L "Time   "
ETUs, BTUs and ETL
.s1
.L "apropos * "
Searches info pages for information on a topic
.L "bye * "
Log out of Empire
.L "country   "
Find out country status
.L "execute   "
Execute a batch file
.L "help * "
Provide information on various topics
.L "info * "
Provide information on various topics
.L "list   "
List commands which are currently legal
.L "players   "
List players currently connected to the game
.L "pray * "
Interacting with the Deity
.L "quit * "
Log out of Empire
.L "version   "
Display parameters of this world
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
