.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject PRODUCING
.in \w'SectorMtypesXX\0\0\0\0'u
.s1
.L "Education   "
How Education is calculated at the update
.L "Happiness   "
How happiness is calculated at the update
.L "Item-types * "
Description of the different types of items
.L "Products * "
Formulas for the production of commodities
.L "Research   "
How Research level is calculated each update
.L "Sector-types *!"
Description of different sector types
.L "Technology   "
How technology level is calculated each update
.s1
.L "production * "
Predicts production of sectors at the next update
.L "start   "
Resume production and repairs
.L "stop   "
Stop production and repairs
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
