.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject SECTORS
.in \w'SectorMownershipXX\0\0\0\0'u
.s1
.L "Bridges   "
Building and destroying bridges
.L "Infrastructure * "
Making your sectors better
.L "Mobility   "
How much mobility stuff costs
.L "Quick-ref * "
A quick reference card for sector types
.L "Sector-ownership * "
Sector ownership
.L "Sector-types *!"
Description of different sector types
.s1
.L "anti * "
anti-terrorist actions
.L "build * "
Build ships, planes, land units, nuclear weapons or bridges
.L "census * "
Report contents of sectors
.L "commodity * "
Report commodities in sectors
.L "designate * "
Specify sector utilization
.L "dump   "
Dump raw sector information
.L "explore * "
Claim unowned land
.L "improve * "
Improve the infrastructure of a sector
.L "lost * "
Report lost items
.L "neweff   "
Find out what the efficiency of a sector will be after the next update
.L "radar * "
Perform radar scan from ship or sector
.L "resource * "
Show the resources of sectors
.L "sinfrastructure * "
Report infrastructure of sectors
.L "spy * "
Snoop on adjacent enemy sectors
.L "territory   "
Assign various sectors to a specific territory
.L "xdump   "
Extended dump of everything under the sun
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
