.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject SERVER
.in \w'OldMempireXX\0\0\0\0'u
.s1
.L "Innards + "
Some details about the inner workings of the server
.s1
.L "Bugs   "
Known bugs in the Empire Server
.L "Chainsaw ! "
Changes from KSU Empire to Chainsaw (1992-93)
.L "Empire2 ! "
Changes from Chainsaw to Empire 2 (1995)
.L "Empire3   "
Changes in Empire 3 (1995-96)
.L "Empire4.0 ! "
Changes in Empire 4.0 (1996-1998)
.L "Empire4.2 ! "
Changes in Empire 4.2 (1998-2005)
.L "Empire4.3 ! "
Changes in Empire 4.3 (2006-2015)
.L "Empire4.4   "
Changes in Empire 4.4 (2015-present)
.L "God   "
Tips on being God
.L "Hidden   "
The HIDDEN option
.L "History   "
Empire Revision History
.L "Merc   "
Changes from KSU code to Merc code (1992)
.L "Old-empire ! "
Differences from 1.2 to UCB Empire
.L "Options   "
Server options
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by + are obsolete.
Topics with unusually long info are marked with a !.
