.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject SHIPS
.in \w'MaintenanceXX\0\0\0\0'u
.s1
.L "Maintenance   "
The cost to maintain ships, planes, and land units.
.L "Mobility   "
How much mobility stuff costs
.L "Ship-types *!"
Description of different types of ships.
.L "Trade-ships * "
How to use trade ships
.s1
.L "assault * "
Attack coastal sector from ship
.L "board * "
Board enemy ship
.L "build * "
Build ships, planes, land units, nuclear weapons or bridges
.L "cargo * "
List the commodities on board your ships
.L "coastwatch * "
Check from sectors for nearby ships
.L "fire * "
Fire artillery from sector/ship/unit on sector/ship
.L "fleetadd   "
Designate members of a \*Qfleet\*U
.L "load * "
Load goods, people, etc onto a ship
.L "lookout * "
Check from ships for other ships and/or sector types
.L "lost * "
Report lost items
.L "ltend   "
Transfer things between a unit and the ship carrying it
.L "mine * "
Drop sea mines from a ship
.L "mission * "
Assign a mission to a ship/plane/unit
.L "name   "
Give a name to a ship
.L "navigate * "
Move ship or fleet around
.L "payoff   "
Find out the current payoff of a trade ship
.L "radar * "
Perform radar scan from ship or sector
.L "retreat   "
Set retreat conditions/paths for ships or fleets
.L "sbmap * "
Big map of all your worldly knowledge around a ship
.L "scrap * "
Scrap a ship, plane, or land unit
.L "scuttle * "
Destroy a ship, plane, or unit
.L "sdump   "
Dump raw ship information
.L "ship * "
Report status of ships
.L "show * "
Characteristics of sectors, units, updates and more
.L "smap * "
Get a map around a ship
.L "sonar * "
Use sonar to look for ships
.L "sstat * "
Report statistics of ship, fleet or ships in a given area
.L "start   "
Resume production and repairs
.L "stop   "
Stop production and repairs
.L "tend * "
Transfer commodities between ships
.L "torpedo * "
Slip a torpedo to some poor sucker (from a sub or ship)
.L "unload * "
Inverse of load (above)
.L "upgrade   "
Update the tech of a ship/unit/plane to the current tech level
.L "xdump   "
Extended dump of everything under the sun
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
