.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject TRANSPORTATION
.in \w'SectorMtypesXX\0\0\0\0'u
.s1
.L "Mobility   "
How much mobility stuff costs
.L "Moving * "
A quick reference for moving things around
.L "Sector-types *!"
Description of different sector types
.s1
.L "fly * "
Fly planes from sector/ship to sector/ship and bomb or snoop
.L "march * "
Move a land unit or units
.L "move * "
Transport ore, civilians, guns, etc
.L "navigate * "
Move ship or fleet around
.L "test   "
Check the effect of a proposed move
.L "transport * "
Move planes or nuclear devices around
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics with unusually long info are marked with a !.
