.\" DO NOT EDIT THIS FILE.  It was automatically generated by mksubj.pl
.TH Subject UPDATES
.in \w'UpdateMsequenceXX\0\0\0\0'u
.s1
.L "Education   "
How Education is calculated at the update
.L "Food   "
How much people eat at the update
.L "Guerrilla   "
Guerrilla warfare
.L "Happiness   "
How happiness is calculated at the update
.L "Maintenance   "
The cost to maintain ships, planes, and land units.
.L "Plague   "
The Plague
.L "Products * "
Formulas for the production of commodities
.L "Research   "
How Research level is calculated each update
.L "Taxes   "
How taxes are calculated
.L "Technology   "
How technology level is calculated each update
.L "Update-sequence   "
The order of events at the update
.s1
.L "budget * "
Look at a national balance sheet
.L "neweff   "
Find out what the efficiency of a sector will be after the next update
.L "production * "
Predicts production of sectors at the next update
.L "show * "
Characteristics of sectors, units, updates and more
.L "start   "
Resume production and repairs
.L "starvation * "
Find out who's going to starve
.L "stop   "
Stop production and repairs
.L "update + "
Find out when the next update will be
.L "zdone   "
Indicate willingness to have an update
.s1
.in 0
For info on a particular topic, type "info <topic>" where <topic> is
one of the topics listed above.
Topics marked by * are the most important and should be read by new players.
Topics marked by + are obsolete.
